import { type Task, TaskPriority, TaskStatus, TaskType } from '^/types';

export const STATUS_OPTIONS = [
  { label: 'Ready to start', color: 'blue' },
  { label: 'In Progress', color: 'orange' },
  { label: 'Waiting for review', color: 'cyan' },
  { label: 'Pending Deploy', color: 'purple' },
  { label: 'Done', color: 'green' },
  { label: 'Stuck', color: 'red' },
];

export const PRIORITY_OPTIONS = [
  { label: 'Critical', color: 'red' },
  { label: 'High', color: 'orange' },
  { label: 'Medium', color: 'yellow' },
  { label: 'Low', color: 'blue' },
  { label: 'Best Effort', color: 'gray' },
];

export const TYPE_OPTIONS = [
  { label: 'Feature Enhancements', color: 'cyan' },
  { label: 'Bug', color: 'red' },
  { label: 'Other', color: 'purple' },
];

export const TASKS: Task[] = [
  {
    id: 1,
    createdAt: '2026-01-01T08:15:30Z',
    title: 'Implement user authentication',
    developer: 'Alice, Bob',
    priority: TaskPriority.CRITICAL,
    status: TaskStatus.IN_PROGRESS,
    type: TaskType.FEATURE,
    'Estimated SP': 5,
    'Actual SP': 4,
  },
  {
    id: 2,
    createdAt: '2026-01-02T09:20:10Z',
    title: 'Fix login page bug',
    developer: 'Bob',
    priority: TaskPriority.HIGH,
    status: TaskStatus.TODO,
    type: TaskType.BUG,
    'Estimated SP': 3,
    'Actual SP': 3,
  },
  {
    id: 3,
    createdAt: '2026-01-03T10:05:45Z',
    title: 'Refactor dashboard layout',
    developer: 'Charlie',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.IN_REVIEW,
    type: TaskType.FEATURE,
    'Estimated SP': 4,
    'Actual SP': 5,
  },
  {
    id: 4,
    createdAt: '2026-01-04T11:00:00Z',
    title: 'Update API documentation',
    developer: 'Alice',
    priority: TaskPriority.LOW,
    status: TaskStatus.DONE,
    type: TaskType.OTHER,
    'Estimated SP': 2,
    'Actual SP': 2,
  },
  {
    id: 5,
    createdAt: '2026-01-05T13:45:22Z',
    title: 'Optimize database queries',
    developer: 'Bob, Charlie',
    priority: TaskPriority.CRITICAL,
    status: TaskStatus.STUCK,
    type: TaskType.BUG,
    'Estimated SP': 6,
    'Actual SP': 7,
  },
  {
    id: 6,
    createdAt: '2026-01-06T14:10:05Z',
    title: 'Add unit tests for payment module',
    developer: 'Charlie',
    priority: TaskPriority.HIGH,
    status: TaskStatus.PENDING_DEPLOY,
    type: TaskType.OTHER,
    'Estimated SP': 4,
    'Actual SP': 4,
  },
  {
    id: 7,
    createdAt: '2026-01-07T15:30:00Z',
    title: 'Develop admin analytics dashboard',
    developer: 'Alice',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.TODO,
    type: TaskType.FEATURE,
    'Estimated SP': 7,
    'Actual SP': 0,
  },
  {
    id: 8,
    createdAt: '2026-01-08T16:40:18Z',
    title: 'Investigate memory leak',
    developer: 'Bob',
    priority: TaskPriority.CRITICAL,
    status: TaskStatus.IN_REVIEW,
    type: TaskType.BUG,
    'Estimated SP': 8,
    'Actual SP': 6,
  },
  {
    id: 9,
    createdAt: '2026-01-09T09:00:00Z',
    title: 'Research new caching strategy',
    developer: 'Charlie',
    priority: TaskPriority.BEST_EFFORT,
    status: TaskStatus.IN_PROGRESS,
    type: TaskType.OTHER,
    'Estimated SP': 2,
    'Actual SP': 2,
  },
  {
    id: 10,
    createdAt: '2026-01-10T10:25:55Z',
    title: 'Integrate third-party payment gateway',
    developer: 'Alice, Bob',
    priority: TaskPriority.HIGH,
    status: TaskStatus.PENDING_DEPLOY,
    type: TaskType.FEATURE,
    'Estimated SP': 6,
    'Actual SP': 6,
  },
  {
    id: 11,
    createdAt: '2026-01-11T11:10:30Z',
    title: 'Improve error logging',
    developer: 'Bob',
    priority: TaskPriority.LOW,
    status: TaskStatus.DONE,
    type: TaskType.OTHER,
    'Estimated SP': 3,
    'Actual SP': 2,
  },
  {
    id: 12,
    createdAt: '2026-01-12T12:55:00Z',
    title: 'Fix CSS issues on mobile',
    developer: 'Charlie',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.STUCK,
    type: TaskType.BUG,
    'Estimated SP': 3,
    'Actual SP': 0,
  },
  {
    id: 13,
    createdAt: '2026-01-13T14:00:00Z',
    title: 'Create deployment scripts',
    developer: 'Alice',
    priority: TaskPriority.HIGH,
    status: TaskStatus.IN_PROGRESS,
    type: TaskType.OTHER,
    'Estimated SP': 4,
    'Actual SP': 4,
  },
  {
    id: 14,
    createdAt: '2026-01-14T15:45:10Z',
    title: 'Migrate database to new server',
    developer: 'Bob, Charlie',
    priority: TaskPriority.CRITICAL,
    status: TaskStatus.TODO,
    type: TaskType.FEATURE,
    'Estimated SP': 7,
    'Actual SP': 0,
  },
  {
    id: 15,
    createdAt: '2026-01-15T16:30:45Z',
    title: 'Conduct API load testing',
    developer: 'Charlie',
    priority: TaskPriority.HIGH,
    status: TaskStatus.IN_REVIEW,
    type: TaskType.OTHER,
    'Estimated SP': 5,
    'Actual SP': 5,
  },
  {
    id: 16,
    createdAt: '2026-01-16T09:15:00Z',
    title: 'Implement two-factor authentication',
    developer: 'Alice, Bob',
    priority: TaskPriority.CRITICAL,
    status: TaskStatus.IN_PROGRESS,
    type: TaskType.FEATURE,
    'Estimated SP': 8,
    'Actual SP': 7,
  },
  {
    id: 17,
    createdAt: '2026-01-17T10:40:20Z',
    title: 'Fix pagination issue on user table',
    developer: 'Bob',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.TODO,
    type: TaskType.BUG,
    'Estimated SP': 4,
    'Actual SP': 0,
  },
  {
    id: 18,
    createdAt: '2026-01-18T11:50:00Z',
    title: 'Upgrade project dependencies',
    developer: 'Charlie, Alice',
    priority: TaskPriority.HIGH,
    status: TaskStatus.PENDING_DEPLOY,
    type: TaskType.OTHER,
    'Estimated SP': 6,
    'Actual SP': 5,
  },
  {
    id: 19,
    createdAt: '2026-01-19T13:00:00Z',
    title: 'Add localization support',
    developer: 'Alice',
    priority: TaskPriority.MEDIUM,
    status: TaskStatus.DONE,
    type: TaskType.FEATURE,
    'Estimated SP': 4,
    'Actual SP': 3,
  },
  {
    id: 20,
    createdAt: '2026-01-20T14:35:50Z',
    title: 'Fix 404 error on settings page',
    developer: 'Bob',
    priority: TaskPriority.CRITICAL,
    status: TaskStatus.IN_PROGRESS,
    type: TaskType.BUG,
    'Estimated SP': 3,
    'Actual SP': 3,
  },
];
